SELECT author_lname FROM `books`;
SELECT author_lname FROM `books` ORDER By author_lname;
SELECT title FROM `books`;
SELECT title FROM `books` ORDER BY title;
SELECT title FROM `books` ORDER BY title DESC;
SELECT released_year FROM `books`;
SELECT released_year FROM `books` ORDER BY released_year;
SELECT released_year FROM `books` ORDER BY released_year DESC;
SELECT title,released_year,pages FROM `books` ORDER BY released_year;
SELECT title,pages FROM `books` ORDER BY released_year;
SELECT title,author_fname,author_lname FROM `books` ORDER BY 2;
SELECT title,author_fname,author_lname FROM `books` ORDER BY 3;
